### ISSUE TITLE
login-response may contain vehicle list

### ISSUE THREAD

**Issue by gym22** [beejjacobs/nissan-connect#2]
the login response may contain a vehicleinfolist instead of a single vehicleinfo:

              "VehicleInfoList": {
                        "VehicleInfo": [
                                {
                                        "charger20066":"false",
                                        "nickname":"LEAF",
                                        "telematicsEnabled":"true",
                                        "vin":"1ABCDEFG2HIJKLM3N"
                                }
                        ],
                        "vehicleInfo": [
                                {
                                        "charger20066":"false",
                                        "nickname":"LEAF",
                                        "telematicsEnabled":"true",
                                        "vin":"1ABCDEFG2HIJKLM3N"
                                }
                        ]
                },

(yes, one with a lower case v and another with upper case V)
currently, in that case, login-response.js throws an exception at line 57

A quick fix to get it going was to add before line 57: 

     if (this.res.hasOwnProperty('VehicleInfoList')) {
        this.res.vehicleInfo = this.res.VehicleInfoList.vehicleInfo;
     }

**Comment by beejjacobs** [comment]
Good to know, thank you. I knew there would be cases I haven't caught because I can only test with my account. Is the second entry just a copy?!

I'll add in your change.

**Comment by gym22** [comment]
With my account, it is just a copy.

**Comment by beejjacobs** [comment]
Okay cool.

Version 1.0.6 has the fix in.
