### ISSUE TITLE
npm repo is not in sync with github

### ISSUE THREAD

**Issue by dernotte** [beejjacobs/nissan-connect#3]
npm repo has a 1.1.0 which seams to be older that the latest 1.0.14 in github. In particular, the bug " add support for a login response with a VehicleInfoList, fixes #2 " is not fix in the official npm repo

**Comment by beejjacobs** [comment]
Please see: https://www.npmjs.com/package/@beejjacobs/nissan-connect which is up to date. The version you're looking at (https://www.npmjs.com/package/nissan-connect) is old.
