### ISSUE TITLE
Release 1.1 is the oldest release but it is the one with the highest number

### ISSUE THREAD

**Issue by ctaschereau** [beejjacobs/nissan-connect#5]
Currently, if I do a "npm install --save nissan-connect", it will install the version 1.1.0. I then have to go into the package.json and manually force a specific version.

I guess that the easiest would simply be to remove the old 1.1.0 release since the new ones offer a lot more functionality.

**Comment by beejjacobs** [comment]
Do `npm install --save @beejjacobs/nissan-connect` - I switched to scoped packaged but left the old one there, and also reset the version when I did.
