### ISSUE TITLE
password encoding error

### ISSUE THREAD

**Issue by johnty** [beejjacobs/nissan-connect#7]
looks like the password encoding is not correct. don't know enough about the process to know why exactly, but hopefully the following helps:

i'm comparing with the encoded password from [pycarwings2](https://github.com/jdhorne/pycarwings2/blob/master/pycarwings2/pycarwings2.py#L158) and the value seems to be different (first 10 characters are the same). if i take the result from the python library and hardcode it into the output of the [encryptPassword](https://github.com/beejjacobs/nissan-connect/blob/master/src/nissan-connect-api.js#L204) function, then everything works.

**Comment by beejjacobs** [comment]
do you get an error when you try to use the API then? It works for me as it is.

**Comment by johnty** [comment]
yes, i get an error when trying to log in when using the result of encryptPassword as is, but if i manually take the output from the pycarwings2 encrypt function, the rest of the library works. will try to dig further to see whats going on...

**Comment by johnty** [comment]
update (short version): i'm an idiot.
(longer version): the password in the config file was wrong.

sorry for the noise. everything works fine. feel free to delete this thread completely.

**Comment by beejjacobs** [comment]
Don't worry that happens to us all! Glad it's working for you.
