### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by rohithzr** [beejjacobs/nissan-connect#9]
using the docs, I am unable to login anymore.
```
{ status: '-2010', message: 'INVALID PARAMS' }
```

debugging a little deeper

```
request:
uri: 'https://gdcportalgw.its-mo.com/api_v180117_NE/gdc/UserLoginRequest.php',
method: 'POST'

response:
{"status":404,"message":"INVALID PARAMS"}
```

**Comment by beejjacobs** [comment]
I get the same error! Sorry I don't have a Leaf anymore (which I'm very sad about); nor the time to test. If you can find out the issue I'd be happy to update the module.

**Comment by beejjacobs** [comment]
FYI I get the same with https://github.com/jdhorne/pycarwings2 and the new URL

**Comment by rohithzr** [comment]
@beejjacobs seems like there have been many changes in the API and no official documentation. We are stuck, it seems.

**Comment by beejjacobs** [comment]
@Rohithzr sadly there never has been; it's the great work done by others which allowed me to write such a module in the first place.

**Comment by jfarinhote** [comment]
Any news on this thread? Where to find documentation for the NISSAN API latest version, or any version?

**Comment by beejjacobs** [comment]
Someone made a pull request which I merged with a new URL. I don't know if that fixed this.

https://github.com/beejjacobs/nissan-connect/pull/10
